### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by siarheisakovich** [Anzhelika-Trockaya/epam-jwd-task1#1]
https://github.com/Anzhelika-Trockaya/epam-jwd-task1/blob/d1fd388f9d2c2e49bf7aa4c15a09c7d3cf5a185f/task1/src/main/java/com/epam/task1/service/ArraySortService.java#L8

test

**Comment by kirillsachevko** [comment]
test comment

**Comment by siarheisakovich** [comment]
test close
